"""Default settings configuration."""
from typing import Any

DEFAULT_SETTINGS: dict[str, dict[str, dict[str, Any]]] = {
    "api_config": {
        "anthropic_api_key": {
            "value": "",
            "value_type": "string",
            "description": "Anthropic API key for Claude access",
            "is_sensitive": True,
            "validation_rules": {"required": False, "pattern": "^sk-ant-.*$"},
        },
        "alpha_vantage_api_key": {
            "value": "",
            "value_type": "string",
            "description": "Alpha Vantage API key for market data",
            "is_sensitive": True,
            "validation_rules": {"required": False},
        },
        "news_api_key": {
            "value": "",
            "value_type": "string",
            "description": "News API key for news aggregation",
            "is_sensitive": True,
            "validation_rules": {"required": False},
        },
        "fred_api_key": {
            "value": "",
            "value_type": "string",
            "description": "FRED API key for economic data",
            "is_sensitive": True,
            "validation_rules": {"required": False},
        },
        "anthropic_rpm": {
            "value": "50",
            "value_type": "integer",
            "description": "Anthropic API requests per minute limit",
            "is_sensitive": False,
            "validation_rules": {"min": 1, "max": 1000},
        },
        "request_timeout": {
            "value": "30",
            "value_type": "integer",
            "description": "Default request timeout in seconds",
            "is_sensitive": False,
            "validation_rules": {"min": 5, "max": 300},
        },
        "max_retries": {
            "value": "3",
            "value_type": "integer",
            "description": "Maximum retry attempts for failed requests",
            "is_sensitive": False,
            "validation_rules": {"min": 0, "max": 10},
        },
    },
    "agent_config": {
        "macro_enabled": {
            "value": "true",
            "value_type": "boolean",
            "description": "Enable Macro Economics Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "macro_model": {
            "value": "claude-sonnet-4-5-20250929",
            "value_type": "string",
            "description": "Claude model for Macro Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "macro_max_tokens": {
            "value": "4000",
            "value_type": "integer",
            "description": "Max tokens for Macro Agent responses",
            "is_sensitive": False,
            "validation_rules": {"min": 100, "max": 16000},
        },
        "macro_cache_ttl": {
            "value": "3600",
            "value_type": "integer",
            "description": "Cache TTL for Macro Agent in seconds",
            "is_sensitive": False,
            "validation_rules": {"min": 60, "max": 86400},
        },
        "geopolitical_enabled": {
            "value": "true",
            "value_type": "boolean",
            "description": "Enable Geopolitical Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "geopolitical_model": {
            "value": "claude-sonnet-4-5-20250929",
            "value_type": "string",
            "description": "Claude model for Geopolitical Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "commodities_enabled": {
            "value": "true",
            "value_type": "boolean",
            "description": "Enable Commodities Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "commodities_model": {
            "value": "claude-sonnet-4-5-20250929",
            "value_type": "string",
            "description": "Claude model for Commodities Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "sentiment_enabled": {
            "value": "true",
            "value_type": "boolean",
            "description": "Enable Sentiment Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "sentiment_model": {
            "value": "claude-sonnet-4-5-20250929",
            "value_type": "string",
            "description": "Claude model for Sentiment Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "fundamentals_enabled": {
            "value": "true",
            "value_type": "boolean",
            "description": "Enable Fundamentals Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "fundamentals_model": {
            "value": "claude-sonnet-4-5-20250929",
            "value_type": "string",
            "description": "Claude model for Fundamentals Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "technical_enabled": {
            "value": "true",
            "value_type": "boolean",
            "description": "Enable Technical Analysis Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "technical_model": {
            "value": "claude-sonnet-4-5-20250929",
            "value_type": "string",
            "description": "Claude model for Technical Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "risk_enabled": {
            "value": "true",
            "value_type": "boolean",
            "description": "Enable Risk Management Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "risk_model": {
            "value": "claude-sonnet-4-5-20250929",
            "value_type": "string",
            "description": "Claude model for Risk Agent",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "aggregation_model": {
            "value": "claude-sonnet-4-5-20250929",
            "value_type": "string",
            "description": "Claude model for Aggregation Engine",
            "is_sensitive": False,
            "validation_rules": None,
        },
    },
    "risk_management": {
        "max_position_size": {
            "value": "5.0",
            "value_type": "float",
            "description": "Maximum position size as percentage of portfolio",
            "is_sensitive": False,
            "validation_rules": {"min": 0.1, "max": 100},
        },
        "max_sector_exposure": {
            "value": "20.0",
            "value_type": "float",
            "description": "Maximum sector exposure as percentage",
            "is_sensitive": False,
            "validation_rules": {"min": 1, "max": 100},
        },
        "max_drawdown": {
            "value": "15.0",
            "value_type": "float",
            "description": "Maximum acceptable drawdown percentage",
            "is_sensitive": False,
            "validation_rules": {"min": 1, "max": 50},
        },
        "correlation_limit": {
            "value": "0.7",
            "value_type": "float",
            "description": "Maximum correlation coefficient between positions",
            "is_sensitive": False,
            "validation_rules": {"min": 0, "max": 1},
        },
        "max_leverage": {
            "value": "1.5",
            "value_type": "float",
            "description": "Maximum leverage multiplier",
            "is_sensitive": False,
            "validation_rules": {"min": 1, "max": 10},
        },
        "portfolio_size": {
            "value": "100000.0",
            "value_type": "float",
            "description": "Portfolio size in USD",
            "is_sensitive": False,
            "validation_rules": {"min": 1000},
        },
    },
    "scheduling": {
        "macro_schedule": {
            "value": "0 9 * * *",
            "value_type": "string",
            "description": "Cron schedule for Macro Agent (daily at 9am)",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "geopolitical_schedule": {
            "value": "0 */6 * * *",
            "value_type": "string",
            "description": "Cron schedule for Geopolitical Agent (every 6 hours)",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "commodities_schedule": {
            "value": "0 */4 * * *",
            "value_type": "string",
            "description": "Cron schedule for Commodities Agent (every 4 hours)",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "sentiment_schedule": {
            "value": "0 */2 * * *",
            "value_type": "string",
            "description": "Cron schedule for Sentiment Agent (every 2 hours)",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "fundamentals_schedule": {
            "value": "0 9 * * 0",
            "value_type": "string",
            "description": "Cron schedule for Fundamentals Agent (weekly)",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "technical_schedule": {
            "value": "*/15 * * * *",
            "value_type": "string",
            "description": "Cron schedule for Technical Agent (every 15 min)",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "risk_schedule": {
            "value": "*/5 * * * *",
            "value_type": "string",
            "description": "Cron schedule for Risk Agent (every 5 min)",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "timezone": {
            "value": "America/New_York",
            "value_type": "string",
            "description": "Timezone for scheduling",
            "is_sensitive": False,
            "validation_rules": None,
        },
    },
    "performance": {
        "token_budget_daily": {
            "value": "1000000",
            "value_type": "integer",
            "description": "Daily token budget",
            "is_sensitive": False,
            "validation_rules": {"min": 1000},
        },
        "token_budget_monthly": {
            "value": "20000000",
            "value_type": "integer",
            "description": "Monthly token budget",
            "is_sensitive": False,
            "validation_rules": {"min": 10000},
        },
        "cost_alert_threshold": {
            "value": "80",
            "value_type": "integer",
            "description": "Alert when budget usage exceeds this percentage",
            "is_sensitive": False,
            "validation_rules": {"min": 1, "max": 100},
        },
        "cache_ttl_default": {
            "value": "3600",
            "value_type": "integer",
            "description": "Default cache TTL in seconds",
            "is_sensitive": False,
            "validation_rules": {"min": 60, "max": 86400},
        },
    },
    "ui_preferences": {
        "theme": {
            "value": "dark",
            "value_type": "string",
            "description": "UI theme (dark/light/auto)",
            "is_sensitive": False,
            "validation_rules": {"enum": ["dark", "light", "auto"]},
        },
        "default_view": {
            "value": "dashboard",
            "value_type": "string",
            "description": "Default view on load",
            "is_sensitive": False,
            "validation_rules": None,
        },
        "refresh_interval": {
            "value": "30",
            "value_type": "integer",
            "description": "Data refresh interval in seconds",
            "is_sensitive": False,
            "validation_rules": {"min": 5, "max": 300},
        },
        "notifications_enabled": {
            "value": "true",
            "value_type": "boolean",
            "description": "Enable browser notifications",
            "is_sensitive": False,
            "validation_rules": None,
        },
    },
    "system": {
        "log_level": {
            "value": "INFO",
            "value_type": "string",
            "description": "Logging level",
            "is_sensitive": False,
            "validation_rules": {"enum": ["DEBUG", "INFO", "WARNING", "ERROR"]},
        },
        "environment": {
            "value": "development",
            "value_type": "string",
            "description": "Environment name",
            "is_sensitive": False,
            "validation_rules": {"enum": ["development", "staging", "production"]},
        },
        "db_pool_size": {
            "value": "10",
            "value_type": "integer",
            "description": "Database connection pool size",
            "is_sensitive": False,
            "validation_rules": {"min": 1, "max": 100},
        },
        "redis_max_connections": {
            "value": "50",
            "value_type": "integer",
            "description": "Redis max connections",
            "is_sensitive": False,
            "validation_rules": {"min": 1, "max": 500},
        },
    },
}


def get_default_value(category: str, key: str, default: Any = None) -> Any:
    """Get default value for a setting."""
    if category in DEFAULT_SETTINGS and key in DEFAULT_SETTINGS[category]:
        return DEFAULT_SETTINGS[category][key].get("value", default)
    return default
